# Generated by Django 5.2.3 on 2025-06-28 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='goal_description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='goal_end',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='goal_start',
            field=models.DateField(null=True),
        ),
    ]
